- src/index.js
> change_emms_hellobar

- src/index.js
> DS-4582_change_hellobar_content

- src/index.js
> DS-4738_fix_link

- src/index.js
> test_branch

- src/index.js
> DS-4822_change_content

- src/index.js
> feat: change hellobar content

- src/index.js
> DS-5097_change_hellobar_content

- src/hellobar.css
- src/index.js
feat: change content and style
> DS-5158_change_hellobar

- src/hellobar.css
> DS-5158_change_color

- src/hellobar.css
- src/index.js
> DS-5159_new_hellobar

- src/hellobar.css
- src/index.js
> DS-5214 hellobar changes

- src/index.js
hello bar content changes
Related to: [Ticket ](https://makingsense.atlassian.net/jira/software/projects/DS/boards/21?selectedIssue=DS-5236)
> DS-5236 hellobar changes

- src/index.js
change hellobar content
Related to: #290
> DS-5236 feat change hellobar

- src/index.js
change hello bar content
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5291)
> DS-5291 change hellobar

- src/index.js
change hellobar
Related to : [Ticket](https://makingsense.atlassian.net/browse/DS-5341)
> DS-5341_change_hellobar

- src/hellobar.css
- src/index.js
change hellobar styles
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5346)
> DS-5346 hellobar changes

- src/index.js
change hellobar content
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5409)
> DS-5409 change hellobar

- src/index.js
change button content
Related to : [Ticket]( [#url](https://makingsense.atlassian.net/jira/software/projects/DS/boards/21?selectedIssue=DS-5409))
> DS-5409_change_hellobar

- src/index.js
add open link in the same tab
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5486)
> DS-5486 onsite hellobar

- src/index.js
change hellobar link
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5523)
> DS-5523 change onsite hellobar link

- src/index.js
change hellobar content
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5509)
> DS-50509 change hellobar content

- src/index.js
https://makingsense.atlassian.net/browse/DS-5610
> DS-5610 HelloBar content update urgency

- package.json
- src/index.js
- yarn.lock
https://github.com/FromDoppler/sites-hellobar/pull/374
> Merge int into main — prepare release

- src/index.js
https://makingsense.atlassian.net/browse/DS-5629
> DS-5629 post content

- src/index.js
> DS-5649-update-hellobar

- src/index.js
change strong style
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5649)
> DS-5649 change strong

- src/index.js
apply anniversary hellobar content
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5658)
> DS-5658 doppler anniversary hellobar

- src/index.js
feat: new hellobar content
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5680)
> DS-5680 new hellobar

- src/index.js
refactor centralize configuration for easier content maintenance & update content chatbot instagram
refactor(hellobar): centralize configuration and improve maintainability
- Consolidate all settings in HELLOBAR_CONFIG at file top
- Rename 'type' to 'style', remove unused constants
- Update content to Instagram chatbot with doppler styles
- Simplify future content updates
DS-5695
https://makingsense.atlassian.net/browse/DS-5695
> refactor centralize configuration for easier maintenance & update content 

- src/index.js
https://makingsense.atlassian.net/browse/DS-5697
> DS-5697 update param cta page conversaciones

- src/index.js
update hellobar content
Related to: [Ticket](https://makingsense.atlassian.net/browse/DS-5774)
> DS-5774 update emms hellobar
